name: Packer + Terraform CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build-ami:
    name: Build Web Server AMI
    runs-on: ubuntu-latest
    outputs:
      ami_id: ${{ steps.set_ami.outputs.ami_id }}
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: "1.9.1"

      - name: Build AMI with Packer
        id: set_ami
        run: |
          packer init packer/webserver-ami.pkr.hcl
          AMI_ID=$(packer build -machine-readable -color=false packer/webserver-ami.pkr.hcl | awk -F, '/artifact,0,id/ {print $6}' | awk -F: '{print $2}')
          echo "$AMI_ID"

  # deploy-terraform:
  #   name: Deploy ASG with Terraform
  #   runs-on: ubuntu-latest
  #   env:
  #     AWS_REGION: ${{ secrets.AWS_REGION }}
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Install Terraform
  #       uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: "1.9.0"

  #     - name: Terraform Init
  #       run: terraform init
  #       working-directory: terraform

  #     - name: Terraform Plan
  #       run: terraform plan 
  #       working-directory: terraform

  #     - name: Terraform Apply
  #       run: terraform apply -auto-approve  
  #       working-directory: terraform
