name: Terraform Deploy with Custom AMI

on:
  workflow_dispatch:
    inputs:
      running_instance_id:
        description: "ID of running instance to use as AMI"
        required: true
        default: ""

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.9.0"

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: |
          RUNNING_INSTANCE_ID="${{ github.event.inputs.running_instance_id }}"

          if [ -z "$RUNNING_INSTANCE_ID" ]; then
            echo "Error: running_instance_id is required."
            exit 1
          fi

          terraform apply -auto-approve \
            -var="running_instance_id=$RUNNING_INSTANCE_ID" \
            -var="ami_id=$RUNNING_INSTANCE_ID"
        working-directory: terraform