name: Terraform Deploy with Custom AMI

on:
  workflow_dispatch:
    inputs:
      running_instance_id:
        description: "Enter the ID of the running instance to create an AMI"
        required: true
        default: ""

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    outputs:
       running_instance_id: ${{ github.event.inputs.running_instance_id }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.9.0"

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
        
      - name: Terraform Plan
        run: terraform plan -var "running_instance_id=${{ github.event.inputs.running_instance_id }}"
        working-directory: terraform

      - name: Terraform Apply
        #run: terraform apply -auto-approve -var "running_instance_id=${{ github.event.inputs.running_instance_id }}"
        run: terraform destroy -auto-approve -var "running_instance_id=${{ github.event.inputs.running_instance_id }}"
        working-directory: terraform